set -g status on
set -g status-justify left

set -g status-left '#[bg=colour4,fg=colour232] #S #[bg=colour236,fg=default,nobold] '
set -g status-left-length 32
set -g status-right ''

set -g window-status-separator '#[bg=colour236,fg=colour240] | '

set -g window-status-format '#[bg=colour236,fg=colour245] #I #[fg=colour255,bold]#W '
set -g window-status-current-format '#[bg=colour255,fg=colour245] #I #[fg=colour236,bold]#W '

set -g status-style bg=colour236,fg=colour255
bind-key r respawn-pane -k

# Do not auto rename windows
set-option -g allow-rename off

set -g default-terminal "xterm-ghostty"

# Scroll history
set -g history-limit 100000

# Scroll with mouse
setw -g mouse on

# Vim
set-option -g focus-events on

# PI recommendations
set -g extended-keys on
set -g extended-keys-format csi-u
